# general settings
name: Our_GOPRO
model_type: VideoRecurrentModel
scale: 1
num_gpu: 4  # set num_gpu: 0 for cpu mode
manual_seed: 0


# dataset and data loader settings
datasets:
  train:
    name: GOPRO
    type: GOPRORecurrentDataset
    dataroot_gt: /mnt/mydisk/Our/train/gt
    dataroot_lq: /mnt/mydisk/Our/train/blur
    meta_info_file_train: basicsr/data/meta_info_txt/meta_info_our_ALL_GT.txt
    test_mode: False
    io_backend:
      type: disk

    num_frame: 4
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 2             #16 videos
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: GOPRO
    type: VideoRecurrentSplitClipsTestDataset
    dataroot_gt: /mnt/mydisk/Our/test4/gt
    dataroot_lq: /mnt/mydisk/Our/test4/blur

    cache_data: false
    io_backend:
      type: disk

    num_frame: 4
    num_overlap: 0

# network structures
network_g:
  type: Deblur
  num_feat: 24
  num_block: 15

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [30000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 30000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

  fft_opt:
    type: FFT
    loss_weight: 0.1
    reduction: mean
  #perceptual_opt:
   # type: PerceptualLoss
    


# validation settings
val:
  val_freq: 40000
  flip_seq: false
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 2000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: True
